package servicetypes

import (
	"github.com/uselagoon/build-deploy-tool/internal/helpers"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
)

type ServiceType struct {
	Name                     string
	Ports                    ServicePorts
	Volumes                  ServiceVolume
	Strategy                 appsv1.DeploymentStrategy
	PrimaryContainer         ServiceContainer
	InitContainer            ServiceContainer
	SecondaryContainer       ServiceContainer
	PodSecurityContext       ServicePodSecurityContext
	EnableServiceLinks       bool
	ProvidesPersistentVolume bool
	ConsumesPersistentVolume bool
	AllowAdditionalVolumes   bool
}

type ServicePodSecurityContext struct {
	HasDefault bool
	FSGroup    int64
}

type ServiceContainer struct {
	Name            string
	ImagePullPolicy corev1.PullPolicy
	Container       corev1.Container
	// define additional volumes here, can leverage 'go template' with generator.ServiceValues
	Volumes      []corev1.Volume
	VolumeMounts []corev1.VolumeMount
	Command      []string
	FeatureFlags map[string]bool
	// define additional variables here, this can be used by types that inherit from another type
	EnvVars []corev1.EnvVar
}

type ServiceVolume struct {
	PersistentVolumeSize   string
	PersistentVolumePath   string
	PersistentVolumeType   corev1.PersistentVolumeAccessMode
	SourceFromOtherService string
	Backup                 bool
	BackupConfiguration    BackupConfiguration
}

type BackupConfiguration struct {
	Command       string
	FileExtension string
}

// when defining default ServicePorts for a service, the first port in the list should be the port that could be associated to an ingress
// the name of this port must be `http`
type ServicePorts struct {
	CanChangePort bool
	Ports         []corev1.ServicePort
}

// this is a map that maps all the lagoon service-type that can be provided in the `lagoon.type` label to the default values for that service
var ServiceTypes = map[string]ServiceType{
	"basic":                basic,
	"basic-persistent":     basicPersistent,
	"basic-single":         basicSingle,
	"cli":                  cli,
	"cli-persistent":       cliPersistent,
	"elasticsearch":        elasticsearch,
	"mariadb":              mariadb,
	"mariadb-dbaas":        mariadbDBaaS,
	"mariadb-single":       mariadbSingle,
	"mongodb":              mongodb,
	"mongodb-dbaas":        mongodbDBaaS,
	"mongodb-single":       mongodbSingle,
	"nginx":                nginx,
	"nginx-php":            nginxPHP,
	"nginx-php-persistent": nginxPHPPersistent,
	"node":                 node,
	"node-persistent":      nodePersistent,
	"opensearch":           opensearch,
	"postgres":             postgres,
	"postgres-dbaas":       postgresDBaaS,
	"postgres-single":      postgresSingle,
	"python":               python,
	"python-persistent":    pythonPersistent,
	"redis":                redis,
	"redis-persistent":     redisPersistent,
	"varnish":              varnish,
	"varnish-persistent":   varnishPersistent,
	"solr":                 solr,
	"valkey":               valkey,
	"valkey-persistent":    valkeyPersistent,
	"worker":               worker,
	"worker-persistent":    workerPersistent,
	"rabbitmq":             rabbitmq,
	"external":             external,
}

func IsSupportedType(lagoonType string) bool {
	if _, ok := ServiceTypes[lagoonType]; ok {
		return true
	}
	return true
}

// these service types don't have images
var ignoredImageTypes = []string{
	"mariadb-dbaas",
	"postgres-dbaas",
	"mongodb-dbaas",
}

func IsIgnoredImageType(lagoonType string) bool {
	return helpers.Contains(ignoredImageTypes, lagoonType)
}

// these are lagoon types that support autogenerated routes
var supportedDBTypes = []string{
	"mariadb",
	"mariadb-dbaas",
	"postgres",
	"postgres-dbaas",
	"mongodb",
	"mongodb-dbaas",
}

func IsSupportedDBType(lagoonType string) bool {
	return helpers.Contains(supportedDBTypes, lagoonType)
}

// these are lagoon types that support autogenerated routes
var supportedAutogeneratedTypes = []string{
	// "kibana", //@TODO: don't even need this anymore?
	"basic",
	"basic-persistent",
	"basic-single",
	"node",
	"node-persistent",
	"nginx",
	"nginx-php",
	"nginx-php-persistent",
	"varnish",
	"varnish-persistent",
	"python-persistent",
	"python",
}

func IsAutogeneratedSupported(lagoonType string) bool {
	return helpers.Contains(supportedAutogeneratedTypes, lagoonType)
}

// these are lagoon types that come with resources requiring backups
var typesWithBackups = []string{
	"basic-persistent",
	"basic-single",
	"node-persistent",
	"nginx-php-persistent",
	"python-persistent",
	"varnish-persistent",
	"redis-persistent",
	"solr",
	"elasticsearch",
	"opensearch",
	"rabbitmq",
	"mongodb-dbaas",
	"mariadb-dbaas",
	"postgres-dbaas",
	"mariadb-single",
	"postgres-single",
	"mongodb-single",
}

func IsTypeWithBackups(lagoonType string) bool {
	return helpers.Contains(typesWithBackups, lagoonType)
}

// this is a map that maps old service types to their new service types
var oldServiceMap = map[string]string{
	"mariadb-shared":        "mariadb-dbaas",
	"postgres-shared":       "postgres-dbaas",
	"mongo":                 "mongodb",
	"mongo-shared":          "mongodb-dbaas",
	"mongo-dbaas":           "mongodb-dbaas",
	"mongo-single":          "mongodb-single",
	"python-ckandatapusher": "python",
}

func ConvertOldServiceType(lagoonType string) string {
	if val, ok := oldServiceMap[lagoonType]; ok {
		return val
	}
	return lagoonType
}
