---
apiVersion: backup.appuio.ch/v1alpha1
kind: PreBackupPod
metadata:
  annotations:
    lagoon.sh/branch: main
    lagoon.sh/version: v2.7.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: mariadb-dbaas
    lagoon.sh/buildType: branch
    lagoon.sh/environment: main
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: mariadb
    lagoon.sh/service-type: mariadb-dbaas
    prebackuppod: mariadb
  name: mariadb-prebackuppod
spec:
  backupCommand: |
    /bin/sh -c "if [ ! -z $BACKUP_DB_READREPLICA_HOSTS ]; then BACKUP_DB_HOST=$(echo $BACKUP_DB_READREPLICA_HOSTS | cut -d ',' -f1); fi && dump=$(mktemp) && mysqldump --max-allowed-packet=500M --events --routines --quick --add-locks --no-autocommit --single-transaction --no-create-db --no-data --no-tablespaces -h $BACKUP_DB_HOST -u $BACKUP_DB_USERNAME -p$BACKUP_DB_PASSWORD $BACKUP_DB_DATABASE > $dump && mysqldump --max-allowed-packet=500M --events --routines --quick --add-locks --no-autocommit --single-transaction --no-create-db --ignore-table=$BACKUP_DB_DATABASE.watchdog --no-create-info --no-tablespaces --skip-triggers -h $BACKUP_DB_HOST -u $BACKUP_DB_USERNAME -p$BACKUP_DB_PASSWORD $BACKUP_DB_DATABASE >> $dump && cat $dump && rm $dump"
  fileExtension: .mariadb.sql
  pod:
    metadata: {}
    spec:
      containers:
      - args:
        - sleep
        - infinity
        env:
        - name: BACKUP_DB_HOST
          valueFrom:
            configMapKeyRef:
              key: MARIADB_HOST
              name: lagoon-env
        - name: BACKUP_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              key: MARIADB_USERNAME
              name: lagoon-env
        - name: BACKUP_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MARIADB_PASSWORD
              name: lagoon-env
        - name: BACKUP_DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MARIADB_DATABASE
              name: lagoon-env
        image: https://imagecache.example.com/uselagoon/database-tools:latest
        imagePullPolicy: Always
        name: mariadb-prebackuppod
        resources: {}
