---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    lagoon.sh/branch: environment-name
    lagoon.sh/version: v2.x.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: cronjob-myservice
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: cronjob-cli
    lagoon.sh/buildType: branch
    lagoon.sh/environment: environment-name
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: myservice
    lagoon.sh/service-type: cli
    lagoon.sh/template: cli-0.1.0
  name: cronjob-myservice-my-cronjobbb
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          annotations:
            lagoon.sh/branch: environment-name
            lagoon.sh/configMapSha: 32bf1359ac92178c8909f0ef938257b477708aa0d78a5a15ad7c2d7919adf273
            lagoon.sh/version: v2.x.x
          creationTimestamp: null
          labels:
            app.kubernetes.io/instance: cronjob-myservice
            app.kubernetes.io/managed-by: build-deploy-tool
            app.kubernetes.io/name: cronjob-cli
            lagoon.sh/buildType: branch
            lagoon.sh/environment: environment-name
            lagoon.sh/environmentType: production
            lagoon.sh/project: example-project
            lagoon.sh/service: myservice
            lagoon.sh/service-type: cli
            lagoon.sh/template: cli-0.1.0
        spec:
          containers:
          - command:
            - /lagoon/cronjob.sh
            - sleep 300
            env:
            - name: LAGOON_GIT_SHA
              value: "0"
            - name: SERVICE_NAME
              value: myservice
            envFrom:
            - configMapRef:
                name: lagoon-env
            image: harbor.example.com/example-project/environment-name/myservice@latest
            imagePullPolicy: Always
            name: cronjob-myservice-my-cronjobbb
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
            securityContext: {}
            volumeMounts:
            - mountPath: /var/run/secrets/lagoon/sshkey/
              name: lagoon-sshkey
              readOnly: true
          dnsConfig:
            options:
            - name: timeout
              value: "60"
            - name: attempts
              value: "10"
          enableServiceLinks: false
          imagePullSecrets:
          - name: lagoon-internal-registry-secret
          priorityClassName: lagoon-priority-production
          restartPolicy: Never
          securityContext:
            fsGroup: 10001
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 0
            runAsUser: 10000
          volumes:
          - name: lagoon-sshkey
            secret:
              defaultMode: 420
              secretName: lagoon-sshkey
  schedule: 5 2 * * *
  startingDeadlineSeconds: 240
  successfulJobsHistoryLimit: 0
status: {}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    lagoon.sh/branch: environment-name
    lagoon.sh/version: v2.x.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: cronjob-myservice
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: cronjob-cli
    lagoon.sh/buildType: branch
    lagoon.sh/environment: environment-name
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: myservice
    lagoon.sh/service-type: cli
    lagoon.sh/template: cli-0.1.0
  name: cronjob-myservice-my-other-cronjobbb
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          annotations:
            lagoon.sh/branch: environment-name
            lagoon.sh/configMapSha: 32bf1359ac92178c8909f0ef938257b477708aa0d78a5a15ad7c2d7919adf273
            lagoon.sh/version: v2.x.x
          creationTimestamp: null
          labels:
            app.kubernetes.io/instance: cronjob-myservice
            app.kubernetes.io/managed-by: build-deploy-tool
            app.kubernetes.io/name: cronjob-cli
            lagoon.sh/buildType: branch
            lagoon.sh/environment: environment-name
            lagoon.sh/environmentType: production
            lagoon.sh/project: example-project
            lagoon.sh/service: myservice
            lagoon.sh/service-type: cli
            lagoon.sh/template: cli-0.1.0
        spec:
          containers:
          - command:
            - /lagoon/cronjob.sh
            - env
            env:
            - name: LAGOON_GIT_SHA
              value: "0"
            - name: SERVICE_NAME
              value: myservice
            envFrom:
            - configMapRef:
                name: lagoon-env
            image: harbor.example.com/example-project/environment-name/myservice@latest
            imagePullPolicy: Always
            name: cronjob-myservice-my-other-cronjobbb
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
            securityContext: {}
            volumeMounts:
            - mountPath: /var/run/secrets/lagoon/sshkey/
              name: lagoon-sshkey
              readOnly: true
          dnsConfig:
            options:
            - name: timeout
              value: "60"
            - name: attempts
              value: "10"
          enableServiceLinks: false
          imagePullSecrets:
          - name: lagoon-internal-registry-secret
          priorityClassName: lagoon-priority-production
          restartPolicy: Never
          securityContext:
            fsGroup: 10001
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 0
            runAsUser: 10000
          volumes:
          - name: lagoon-sshkey
            secret:
              defaultMode: 420
              secretName: lagoon-sshkey
  schedule: 25 6 * * *
  startingDeadlineSeconds: 240
  successfulJobsHistoryLimit: 0
status: {}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    lagoon.sh/branch: environment-name
    lagoon.sh/version: v2.x.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: cronjob-myservice-persist
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: cronjob-cli-persistent
    lagoon.sh/buildType: branch
    lagoon.sh/environment: environment-name
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: myservice-persist
    lagoon.sh/service-type: cli-persistent
    lagoon.sh/template: cli-persistent-0.1.0
  name: cronjob-myservice-my-cronjobbb
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          annotations:
            lagoon.sh/branch: environment-name
            lagoon.sh/configMapSha: 32bf1359ac92178c8909f0ef938257b477708aa0d78a5a15ad7c2d7919adf273
            lagoon.sh/version: v2.x.x
          creationTimestamp: null
          labels:
            app.kubernetes.io/instance: cronjob-myservice-persist
            app.kubernetes.io/managed-by: build-deploy-tool
            app.kubernetes.io/name: cronjob-cli-persistent
            lagoon.sh/buildType: branch
            lagoon.sh/environment: environment-name
            lagoon.sh/environmentType: production
            lagoon.sh/project: example-project
            lagoon.sh/service: myservice-persist
            lagoon.sh/service-type: cli-persistent
            lagoon.sh/template: cli-persistent-0.1.0
        spec:
          containers:
          - command:
            - /lagoon/cronjob.sh
            - sleep 300
            env:
            - name: LAGOON_GIT_SHA
              value: "0"
            - name: SERVICE_NAME
              value: myservice-persist
            envFrom:
            - configMapRef:
                name: lagoon-env
            image: harbor.example.com/example-project/environment-name/myservice-persistent@latest
            imagePullPolicy: Always
            name: cronjob-myservice-my-cronjobbb
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
            securityContext: {}
            volumeMounts:
            - mountPath: /var/run/secrets/lagoon/sshkey/
              name: lagoon-sshkey
              readOnly: true
            - mountPath: /storage/data/php
              name: nginx-php-twig
            - mountPath: /storage/data
              name: nginx-php
          dnsConfig:
            options:
            - name: timeout
              value: "60"
            - name: attempts
              value: "10"
          enableServiceLinks: false
          imagePullSecrets:
          - name: lagoon-internal-registry-secret
          priorityClassName: lagoon-priority-production
          restartPolicy: Never
          securityContext:
            fsGroup: 10001
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 0
            runAsUser: 10000
          volumes:
          - name: lagoon-sshkey
            secret:
              defaultMode: 420
              secretName: lagoon-sshkey
          - emptyDir: {}
            name: nginx-php-twig
          - name: nginx-php
            persistentVolumeClaim:
              claimName: nginx-php
  schedule: 5 2 * * *
  startingDeadlineSeconds: 240
  successfulJobsHistoryLimit: 0
status: {}
