apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-persistent.fullname" . }}
  labels:
    {{- include "node-persistent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "node-persistent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "node-persistent.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ .Values.persistentStorage.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.name }}
      priorityClassName: {{ include "node-persistent.lagoon-priority" . }}
      enableServiceLinks: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: {{ .Values.images | quote }}
          name: "node-persistent"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            ## LAGOON_GIT_SHA is injected directly and not loaded via `lagoon-env` config
            ## This will cause the cli to redeploy on every deployment, even the files have not changed
            - name: LAGOON_GIT_SHA
              value: {{ .Values.gitSha | quote }}
            - name: CRONJOBS
              value: {{ .Values.cronjobs | quote }}
          envFrom:
            - configMapRef:
                name: lagoon-env
          volumeMounts:
            - name: {{ .Values.persistentStorage.name }}
              mountPath: {{ .Values.persistentStorage.path | quote }}
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
