apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentStorage.name | quote }}
  annotations:
    appuio.ch/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
    # storageClassName: {{ .Values.persistentStorageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistentStorage.size | quote }}
