builds:
- dir: .
  ldflags:
  - >
    -s -w -X github.com/uselagoon/build-deploy-tool/cmd.bdtBuild={{.Date}}
    -X "github.com/uselagoon/build-deploy-tool/cmd.goVersion={{.Env.GOVERSION}}"
    -X github.com/uselagoon/build-deploy-tool/cmd.bdtVersion={{.Version}}
  env:
  - CGO_ENABLED=0
