version: '2'
services:
  node:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: node.dockerfile
    labels:
      lagoon.type: node
    volumes:
      - .:/app:delegated
    environment:
      - LAGOON_LOCALDEV_HTTP_PORT=3000
      - LAGOON_ROUTE=http://node.docker.amazee.io

  mariadb:
    image: uselagoon/mariadb-10.5-drupal:latest
    labels:
      lagoon.type: mariadb
      lando.type: mariadb-drupal
    ports:
      - "3306" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`

  elasticsearch:
    image: uselagoon/elasticsearch-7:latest
    labels:
      lagoon.type: elasticsearch
      lando.type: elasticsearch
    ports:
      - "9200" # exposes the port 9200 with a random local port, find it with `docker-compose port elasticsearch 9200`
    volumes:
      - search:/usr/share/elasticsearch/data

networks:
  amazeeio-network:
    external: true

volumes:
  search:
    {}