---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    k8up.io/backup: "true"
    k8up.syn.tools/backup: "true"
    lagoon.sh/branch: environment-name
    lagoon.sh/version: v2.x.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: myservice
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: basic-single
    lagoon.sh/buildType: branch
    lagoon.sh/environment: environment-name
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: myservice
    lagoon.sh/service-type: basic-single
    lagoon.sh/template: basic-single-0.1.0
  name: myservice
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
