---
apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  annotations:
    lagoon.sh/prBaseBranch: main2
    lagoon.sh/prHeadBranch: main
    lagoon.sh/prNumber: "123"
    lagoon.sh/version: v2.7.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: k8up-lagoon-backup-schedule
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: k8up-schedule
    lagoon.sh/buildType: pullrequest
    lagoon.sh/environment: main
    lagoon.sh/environmentType: development
    lagoon.sh/project: example-project
    lagoon.sh/service: k8up-lagoon-backup-schedule
    lagoon.sh/service-type: k8up-schedule
    lagoon.sh/template: k8up-schedule-0.1.0
  name: k8up-lagoon-backup-schedule
spec:
  backend:
    repoPasswordSecretRef:
      key: repo-pw
      name: baas-repo-pw
    s3:
      accessKeyIDSecretRef:
        key: access-key
        name: lagoon-baas-custom-backup-credentials
      bucket: baas-example-project
      secretAccessKeySecretRef:
        key: secret-key
        name: lagoon-baas-custom-backup-credentials
  backup:
    resources: {}
    schedule: 3,33 12 * * *
  check:
    resources: {}
    schedule: 48 5 * * 1
  prune:
    resources: {}
    retention:
      keepDaily: 7
      keepMonthly: 1
      keepWeekly: 6
    schedule: 48 3 * * 0
  resourceRequirementsTemplate: {}
status: {}
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: lagoon-baas-custom-backup-credentials
stringData:
  access-key: abcdefg
  secret-key: abcdefg1234567
