{{- range $cronjobName, $cronjobConfig := .Values.nativeCronjobs }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-{{ $.Release.Name }}-{{ $cronjobName }}
  labels:
    {{- include "cli-persistent.labels" $ | nindent 4 }}
  annotations:
    {{- include "cli-persistent.annotations" $ | nindent 4 }}
spec:
  schedule: {{ $cronjobConfig.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        {{- include "cli-persistent.labels" $ | nindent 8 }}
      annotations:
        {{- include "cli-persistent.annotations" $ | nindent 8 }}
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            {{- include "cli-persistent.labels" $ | nindent 12 }}
          annotations:
            {{- include "cli-persistent.annotations" $ | nindent 12 }}
        spec:
        {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          priorityClassName: {{ include "cli-persistent.lagoonPriority" $ }}
          enableServiceLinks: false
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          volumes:
            - name: lagoon-sshkey
              secret:
                defaultMode: 420
                secretName: lagoon-sshkey
          containers:
            - image: {{ $.Values.image | quote }}
              name: cronjob-{{ $.Release.Name }}-{{ $cronjobName }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              imagePullPolicy: {{ $.Values.imagePullPolicy }}
              command:
                - /lagoon/cronjob.sh
                - {{ $cronjobConfig.command | quote }}
              env:
                - name: LAGOON_GIT_SHA
                  value: {{ $.Values.gitSha | quote }}
                - name: SERVICE_NAME
                  value: {{ $.Release.Name | quote }}
              envFrom:
                - configMapRef:
                    name: lagoon-env
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
              volumeMounts:
                - mountPath: /var/run/secrets/lagoon/sshkey/
                  name: lagoon-sshkey
                  readOnly: true
          restartPolicy: Never
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml $ | nindent 12 }}
          {{- end }}
        {{- with $.Values.affinity }}
          affinity:
            {{- toYaml $ | nindent 12 }}
        {{- end }}
          tolerations:
            - effect: NoSchedule
              key: lagoon/build
              operator: Exists
            {{- toYaml $.Values.tolerations | nindent 12 }}
{{- end }}
