---
apiVersion: mongodb.amazee.io/v1
kind: MongoDBConsumer
metadata:
  annotations:
    lagoon.sh/branch: environment-with-really-really-reall-3fdb
    lagoon.sh/version: v2.x.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: mongodb-dbaas
    lagoon.sh/buildType: branch
    lagoon.sh/environment: environment-with-really-really-reall-3fdb
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: mongo
    lagoon.sh/service-type: mongodb-dbaas
    lagoon.sh/template: mongodb-dbaas-0.1.0
  name: mongo
spec:
  consumer:
    auth:
      tls: false
    services: {}
  environment: development
  provider:
    auth:
      tls: false
status: {}
