apiVersion: mongodb.amazee.io/v1
kind: MongoDBConsumer
metadata:
  name: {{ include "mongodb-dbaas.fullname" . }}
  labels:
    {{- include "mongodb-dbaas.labels" . | nindent 4 }}
  annotations:
    {{- include "mongodb-dbaas.annotations" . | nindent 4 }}

spec:
  environment: {{ .Values.environment}}
