apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "solr.fullname" . }}
  labels:
    {{- include "solr.labels" . | nindent 4 }}
    {{- if .Values.useSpot }}
    lagoon.sh/spot: {{ .Values.useSpot | quote }}
    {{- end }}
  annotations:
    {{- include "solr.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "solr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "solr.labels" . | nindent 8 }}
        {{- include "solr.datadogLabels" . | nindent 8 }}
        {{- if .Values.useSpot }}
        lagoon.sh/spot: {{ .Values.useSpot | quote }}
        {{- end }}
      annotations:
        {{- include "solr.annotations" . | nindent 8 }}
        k8up.syn.tools/backupcommand: /bin/sh -c 'tar -cf - -C {{ .Values.persistentStorage.path | quote }} --exclude="lost\+found" . || [ $? -eq 1 ]'
        k8up.syn.tools/file-extension: .{{ include "solr.fullname" . }}.tar
        lagoon.sh/configMapSha: {{ .Values.configMapSha | quote }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ include "solr.persistentStorageName" . }}
          persistentVolumeClaim:
            claimName: {{ include "solr.persistentStorageName" . }}
      {{- if .Values.dynamicSecretVolumes }}
        {{- toYaml .Values.dynamicSecretVolumes | nindent 8 }}
      {{- end }}
      priorityClassName: {{ include "solr.lagoonPriority" . }}
      enableServiceLinks: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: {{ .Values.image | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8983
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 90
            timeoutSeconds: 3
            failureThreshold: 5
          envFrom:
            - configMapRef:
                name: lagoon-env
          env:
            - name: CRONJOBS
              value: {{ .Values.inPodCronjobs | quote }}
          volumeMounts:
            - name: {{ include "solr.persistentStorageName" . }}
              mountPath: {{ .Values.persistentStorage.path | quote }}
          {{- if .Values.dynamicSecretMounts }}
            {{- toYaml .Values.dynamicSecretMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
