# Default values for custom-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host: ''
hsts: 'null'
tls_acme: true
insecure: Allow
service: ''
annotations: {}

ingressmonitorcontroller:
  enabled: 'false'
  interval: '60'
  alertContacts: 'unconfigured'
