apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
  annotations:
    {{- include "kibana.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5601
      protocol: TCP
      name: 5601-tcp
  selector:
    {{- include "kibana.selectorLabels" . | nindent 4 }}
