apiVersion: v1
kind: Service
metadata:
  name: {{ include "varnish.fullname" . }}
  labels:
    {{- include "varnish.labels" . | nindent 4 }}
  annotations:
    {{- include "varnish.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 6082
      targetPort: 6082
      protocol: TCP
      name: controlport
  selector:
    {{- include "varnish.selectorLabels" . | nindent 4 }}
