apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-persistent.fullname" . }}
  labels:
    {{- include "redis-persistent.labels" . | nindent 4 }}
  annotations:
    {{- include "redis-persistent.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
      name: 6379-tcp
  selector:
    {{- include "redis-persistent.selectorLabels" . | nindent 4 }}
