{{ if .Capabilities.APIVersions.Has "backup.appuio.ch/v1alpha1/PreBackupPod" }}
apiVersion: backup.appuio.ch/v1alpha1
kind: PreBackupPod
metadata:
  name: {{ include "varnish-persistent.fullname" . }}-prebackuppod
  labels:
    {{- include "varnish-persistent.labels" . | nindent 4 }}
  annotations:
    {{- include "varnish-persistent.annotations" . | nindent 4 }}
spec:
  backupCommand: /bin/sh -c "/bin/busybox tar -cf - -C {{ .Values.persistentStorage.name }} ."
  fileExtension: .{{ include "varnish-persistent.fullname" . }}.tar
  pod:
    metadata:
      labels:
        prebackuppod: {{ include "varnish-persistent.fullname" . }}
        {{- include "varnish-persistent.labels" . | nindent 8 }}
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: service
                      operator: In
                      values:
                        - {{ include "varnish-persistent.fullname" . }}
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - args:
            - sleep
            - '3600'
          envFrom:
            - configMapRef:
                name: lagoon-env
          image: alpine
          imagePullPolicy: Always
          name: {{ include "varnish-persistent.fullname" . }}-prebackuppod
          volumeMounts:
            - name: {{ .Values.persistentStorage.name }}
              mountPath: {{ .Values.persistentStorage.path | quote }}
      volumes:
        - name: {{ .Values.persistentStorage.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentStorage.name }}
{{ end }}

