apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentStorage.name | quote }}
  labels:
    {{- include "varnish-persistent.labels" . | nindent 4 }}
  annotations:
    appuio.ch/backup: "false"
    {{- include "varnish-persistent.annotations" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
    # storageClassName: {{ .Values.persistentStorage.class | quote }}
  resources:
    requests:
      storage: {{ .Values.persistentStorage.size | quote }}
