{{- if and (.Values.customBackupLocation.accessKey) (.Values.customBackupLocation.secretKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: lagoon-baas-custom-backup-credentials
  labels:
    {{- include "k8up-schedule.labels" . | nindent 4 }}
  annotations:
    {{- include "k8up-schedule.annotations" . | nindent 4 }}
stringData:
  access-key: {{ .Values.customBackupLocation.accessKey }}
  secret-key: {{ .Values.customBackupLocation.secretKey }}
{{ end }}