{{- if and (.Values.customRestoreLocation.access-key) (.Values.customRestoreLocation.secret-key) }}
apiVersion: v1
kind: Secret
metadata:
  name: lagoon-baas-custom-restore-credentials
  labels:
    {{- include "k8up-schedule.labels" . | nindent 4 }}
  annotations:
    {{- include "k8up-schedule.annotations" . | nindent 4 }}
stringData:
  access-key: {{ .Values.customRestoreLocation.access-key }}
  secret-key: {{ .Values.customRestoreLocation.secret-key }}
{{ end }}