{{- if and (.Values.customRestoreLocation.accessKey) (.Values.customRestoreLocation.secretKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: lagoon-baas-custom-restore-credentials
  labels:
    {{- include "k8up-schedule.labels" . | nindent 4 }}
  annotations:
    {{- include "k8up-schedule.annotations" . | nindent 4 }}
stringData:
  access-key: {{ .Values.customRestoreLocation.accessKey }}
  secret-key: {{ .Values.customRestoreLocation.secretKey }}
{{ end }}