apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  name: {{ include "k8up-schedule.fullname" . }}
  labels:
    {{- include "k8up-schedule.labels" . | nindent 4 }}
  annotations:
    {{- include "k8up-schedule.annotations" . | nindent 4 }}
spec:
  backend:
    repoPasswordSecretRef:
      key: repo-pw
      name: baas-repo-pw
    s3:
      bucket: '{{ .Values.baasBucketName }}'
  backup:
    schedule: '{{ .Values.backup.schedule }}'
  check:
    schedule: '{{ .Values.check.schedule }}'
  prune:
    retention:
      keepDaily: '{{ .Values.prune.retention.keepDaily }}'
      keepWeekly: '{{ .Values.prune.retention.keepWeekly }}'
      keepMonthly: '{{ .Values.prune.retention.keepMonthly }}'
    schedule: '{{ .Values.prune.schedule }}'
