apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "elasticsearch.persistentStorageName" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  annotations:
    k8up.syn.tools/backup: "false"
    {{- include "elasticsearch.annotations" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentStorage.size | quote }}
