apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-php-persistent.persistentStorageName" . }}
  labels:
    {{- include "nginx-php-persistent.labels" . | nindent 4 }}
  annotations:
    {{- include "nginx-php-persistent.annotations" . | nindent 4 }}
  annotations:
    appuio.ch/backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: bulk
  resources:
    requests:
      storage: {{ .Values.persistentStorage.size | quote }}
