apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-single.fullname" . }}
  labels:
    {{- include "postgres-single.labels" . | nindent 4 }}
    {{- if .Values.useSpot }}
    lagoon.sh/spot: {{ .Values.useSpot | quote }}
    {{- end }}
  annotations:
    {{- include "postgres-single.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "postgres-single.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres-single.labels" . | nindent 8 }}
        {{- if .Values.useSpot }}
        lagoon.sh/spot: {{ .Values.useSpot | quote }}
        {{- end }}
      annotations:
        {{- include "postgres-single.annotations" . | nindent 8 }}
        k8up.syn.tools/backupcommand: /bin/sh -c "PGPASSWORD=${{ regexReplaceAll "\\W+" .Release.Name "_" | upper }}_PASSWORD pg_dump --host=localhost --port=${{ regexReplaceAll "\\W+" .Release.Name "_" | upper }}_SERVICE_PORT --dbname=${{ regexReplaceAll "\\W+" .Release.Name "_" | upper }}_DB --username=${{ regexReplaceAll "\\W+" .Release.Name "_" | upper }}_USER --format=t -w"
        k8up.syn.tools/file-extension: .{{ include "postgres-single.fullname" . }}.tar
        lagoon.sh/configMapSha: {{ .Values.configMapSha | quote }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ include "postgres-single.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ include "postgres-single.fullname" . }}
      {{- if .Values.dynamicSecretVolumes }}
        {{- toYaml .Values.dynamicSecretVolumes | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: CRONJOBS
              value: {{ .Values.inPodCronjobs | toYaml | indent 14 | trim }}
            - name: LAGOON_GIT_SHA
              value: {{ .Values.gitSha | quote }}
          envFrom:
            - configMapRef:
                name: lagoon-env
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 1
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 120
            periodSeconds: 5
          volumeMounts:
            - name: {{ include "postgres-single.fullname" . }}
              mountPath: {{ .Values.persistentStorage.path | quote }}
          {{- if .Values.dynamicSecretMounts }}
            {{- toYaml .Values.dynamicSecretMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
