package lagoon

// BuildValues is the values file data generated by the lagoon build
type BuildValues struct {
	Project            string `json:"project"`
	Environment        string `json:"environment"`
	EnvironmentType    string `json:"environmentType"`
	Namespace          string `json:"namespace"`
	GitSha             string `json:"gitSha"`
	BuildType          string `json:"buildType"`
	Kubernetes         string `json:"kubernetes"`
	LagoonVersion      string `json:"lagoonVersion"`
	ActiveEnvironment  string `json:"activeEnvironment"`
	StandbyEnvironment string `json:"standbyEnvironment"`
	PodSecurityContext struct {
		FsGroup    int `json:"fsGroup"`
		RunAsGroup int `json:"runAsGroup"`
		RunAsUser  int `json:"runAsUser"`
	} `json:"podSecurityContext"`
	ImagePullSecrets []struct {
		Name string `json:"name"`
	} `json:"imagePullSecrets"`
	Branch       string `json:"branch"`
	PRNumber     string `json:"prNumber"`
	PRTitle      string `json:"prTitle"`
	PRHeadBranch string `json:"prHeadBranch"`
	PRBaseBranch string `json:"prBaseBranch"`
	Fastly       struct {
		ServiceID     string `json:"serviceId"`
		APISecretName string `json:"apiSecretName"`
		Watch         bool   `json:"watch"`
	} `json:"fastly"`
	ConfigMapSha               string                   `json:"configMapSha"`
	Route                      string                   `json:"route"`
	Routes                     []string                 `json:"routes"`
	AutogeneratedRoutes        []string                 `json:"autogeneratedRoutes"`
	RoutesAutogeneratePrefixes []string                 `json:"routesAutogeneratePrefixes"`
	Services                   map[string]ServiceValues `json:"services"`
}

// ServiceValues is the values for a specific service used by a lagoon build
type ServiceValues struct {
	Name                          string                   `json:"name"`
	TypeName                      string                   `json:"typeName"`
	Type                          string                   `json:"type"`
	AutogeneratedRoutesEnabled    bool                     `json:"autogeneratedRoutesEnabled"`
	AutogeneratedRoutesTLSAcme    bool                     `json:"autogeneratedRoutesTLSAcme"`
	AutogeneratedRouteDomain      string                   `json:"autogeneratedRouteDomain"`
	ShortAutogeneratedRouteDomain string                   `json:"shortAutogeneratedRouteDomain"`
	DBaaSEnvironment              string                   `json:"dbaasEnvironment"`
	NativeCronjobs                map[string]CronjobValues `json:"nativeCronjobs"`
	InPodCronjobs                 string                   `json:"inPodCronjobs"`
}

// CronjobValues is the values for cronjobs
type CronjobValues struct {
	Schedule string `json:"schedule"`
	Command  string `json:"command"`
}
