apiVersion: mariadb.amazee.io/v1
kind: MariaDBConsumer
metadata:
  name: {{ include "mariadb-dbaas.fullname" . }}
  labels:
    {{- include "mariadb-dbaas.labels" . | nindent 4 }}
  annotations:
    {{- include "mariadb-dbaas.annotations" . | nindent 4 }}
spec:
  environment: {{ .Values.environment}}
