package cmd

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"
	"time"

	"github.com/uselagoon/build-deploy-tool/internal/dbaasclient"
)

func TestIdentifyRoute(t *testing.T) {
	type args struct {
		alertContact       string
		statusPageID       string
		projectName        string
		environmentName    string
		branch             string
		prNumber           string
		prHeadBranch       string
		prBaseBranch       string
		environmentType    string
		buildType          string
		activeEnvironment  string
		standbyEnvironment string
		cacheNoCache       string
		serviceID          string
		secretPrefix       string
		projectVars        string
		envVars            string
		lagoonVersion      string
		lagoonYAML         string
		valuesFilePath     string
		templatePath       string
	}
	tests := []struct {
		name        string
		args        args
		want        string
		wantJSON    string
		wantRemain  []string
		wantautoGen []string
	}{
		{
			name: "test1 check LAGOON_FASTLY_SERVICE_IDS with secret no values",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"},{"name":"LAGOON_FASTLY_SERVICE_IDS","value":"example.com:service-id:true:annotationscom","scope":"build"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test1/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://example.com",
			wantRemain:  []string{"https://node-example-project-main.example.com", "https://example.com"},
			wantautoGen: []string{"https://node-example-project-main.example.com"},
			wantJSON:    `{"primary":"https://example.com","secondary":["https://node-example-project-main.example.com","https://example.com"],"autogenerated":["https://node-example-project-main.example.com"]}`,
		},
		{
			name: "test2 check LAGOON_FASTLY_SERVICE_IDS no secret and no values",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"},{"name":"LAGOON_FASTLY_SERVICE_IDS","value":"example.com:service-id:true","scope":"build"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test2/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://example.com",
			wantRemain:  []string{"https://node-example-project-main.example.com", "https://example.com"},
			wantautoGen: []string{"https://node-example-project-main.example.com"},
			wantJSON:    `{"primary":"https://example.com","secondary":["https://node-example-project-main.example.com","https://example.com"],"autogenerated":["https://node-example-project-main.example.com"]}`,
		},
		{
			name: "test3 check LAGOON_FASTLY_SERVICE_ID no secret and no values",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"},{"name":"LAGOON_FASTLY_SERVICE_ID","value":"service-id:true","scope":"build"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test3/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://example.com",
			wantRemain:  []string{"https://node-example-project-main.example.com", "https://example.com"},
			wantautoGen: []string{"https://node-example-project-main.example.com"},
			wantJSON:    `{"primary":"https://example.com","secondary":["https://node-example-project-main.example.com","https://example.com"],"autogenerated":["https://node-example-project-main.example.com"]}`,
		},
		{
			name: "test4 check no fastly and no values",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test4/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://example.com",
			wantRemain:  []string{"https://node-example-project-main.example.com", "https://example.com"},
			wantautoGen: []string{"https://node-example-project-main.example.com"},
			wantJSON:    `{"primary":"https://example.com","secondary":["https://node-example-project-main.example.com","https://example.com"],"autogenerated":["https://node-example-project-main.example.com"]}`,
		},
		{
			name: "test5 multiproject1 no values",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "multiproject1",
				environmentName: "multiproject",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "multiproject",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test5/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://multiproject1.com",
			wantRemain:  []string{"https://node-multiproject1-multiproject.example.com", "https://multiproject1.com"},
			wantautoGen: []string{"https://node-multiproject1-multiproject.example.com"},
			wantJSON:    `{"primary":"https://multiproject1.com","secondary":["https://node-multiproject1-multiproject.example.com","https://multiproject1.com"],"autogenerated":["https://node-multiproject1-multiproject.example.com"]}`,
		},
		{
			name: "test6 multiproject2 no values",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "multiproject2",
				environmentName: "multiproject",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "multiproject",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test6/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://multiproject2.com",
			wantRemain:  []string{"https://node-multiproject2-multiproject.example.com", "https://multiproject2.com"},
			wantautoGen: []string{"https://node-multiproject2-multiproject.example.com"},
			wantJSON:    `{"primary":"https://multiproject2.com","secondary":["https://node-multiproject2-multiproject.example.com","https://multiproject2.com"],"autogenerated":["https://node-multiproject2-multiproject.example.com"]}`,
		},
		{
			name: "test7 multidomain no values",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test7/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://example.com",
			wantRemain:  []string{"https://node-example-project-main.example.com", "https://example.com", "https://www.example.com"},
			wantautoGen: []string{"https://node-example-project-main.example.com"},
			wantJSON:    `{"primary":"https://example.com","secondary":["https://node-example-project-main.example.com","https://example.com","https://www.example.com"],"autogenerated":["https://node-example-project-main.example.com"]}`,
		},
		{
			name: "test8 multidomain no values",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "branch-routes",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "branch/routes",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test8/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://customdomain-will-be-main-domain.com",
			wantRemain:  []string{"https://node-example-project-branch-routes.example.com", "https://customdomain-will-be-main-domain.com", "https://customdomain-will-be-not-be-main-domain.com"},
			wantautoGen: []string{"https://node-example-project-branch-routes.example.com"},
			wantJSON:    `{"primary":"https://customdomain-will-be-main-domain.com","secondary":["https://node-example-project-branch-routes.example.com","https://customdomain-will-be-main-domain.com","https://customdomain-will-be-not-be-main-domain.com"],"autogenerated":["https://node-example-project-branch-routes.example.com"]}`,
		},
		{
			name: "test9 active no values",
			args: args{
				alertContact:      "alertcontact",
				statusPageID:      "statuspageid",
				projectName:       "example-project",
				environmentName:   "main",
				environmentType:   "production",
				activeEnvironment: "main",
				buildType:         "branch",
				lagoonVersion:     "v2.7.x",
				branch:            "main",
				projectVars:       `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:           `[]`,
				secretPrefix:      "fastly-api-",
				lagoonYAML:        "../test-resources/identify-ingress/test9/lagoon.yml",
				templatePath:      "../test-resources/output",
			},
			want:        "https://active.example.com",
			wantRemain:  []string{"https://node-example-project-main.example.com", "https://main.example.com", "https://active.example.com"},
			wantautoGen: []string{"https://node-example-project-main.example.com"},
			wantJSON:    `{"primary":"https://active.example.com","secondary":["https://node-example-project-main.example.com","https://main.example.com","https://active.example.com"],"autogenerated":["https://node-example-project-main.example.com"]}`,
		},
		{
			name: "test10 standby no values",
			args: args{
				alertContact:       "alertcontact",
				statusPageID:       "statuspageid",
				projectName:        "example-project",
				environmentName:    "main2",
				environmentType:    "production",
				buildType:          "branch",
				standbyEnvironment: "main2",
				lagoonVersion:      "v2.7.x",
				branch:             "main2",
				projectVars:        `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:            `[]`,
				secretPrefix:       "fastly-api-",
				lagoonYAML:         "../test-resources/identify-ingress/test10/lagoon.yml",
				templatePath:       "../test-resources/output",
			},
			want:        "https://standby.example.com",
			wantRemain:  []string{"https://node-example-project-main2.example.com", "https://main2.example.com", "https://standby.example.com"},
			wantautoGen: []string{"https://node-example-project-main2.example.com"},
			wantJSON:    `{"primary":"https://standby.example.com","secondary":["https://node-example-project-main2.example.com","https://main2.example.com","https://standby.example.com"],"autogenerated":["https://node-example-project-main2.example.com"]}`,
		},
		{
			name: "test11 no custom ingress",
			args: args{
				alertContact:       "alertcontact",
				statusPageID:       "statuspageid",
				projectName:        "example-project",
				environmentName:    "no-ingress",
				environmentType:    "production",
				buildType:          "branch",
				standbyEnvironment: "no-ingress",
				lagoonVersion:      "v2.7.x",
				branch:             "main2",
				projectVars:        `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:            `[]`,
				secretPrefix:       "fastly-api-",
				lagoonYAML:         "../test-resources/identify-ingress/test11/lagoon.yml",
				templatePath:       "../test-resources/output",
			},
			want:        "https://node-example-project-no-ingress.example.com",
			wantRemain:  []string{"https://node-example-project-no-ingress.example.com"},
			wantautoGen: []string{"https://node-example-project-no-ingress.example.com"},
			wantJSON:    `{"primary":"https://node-example-project-no-ingress.example.com","secondary":["https://node-example-project-no-ingress.example.com"],"autogenerated":["https://node-example-project-no-ingress.example.com"]}`,
		},
		{
			name: "test12 no custom ingress",
			args: args{
				alertContact:       "alertcontact",
				statusPageID:       "statuspageid",
				projectName:        "example-project",
				environmentName:    "no-ingress",
				environmentType:    "production",
				buildType:          "branch",
				standbyEnvironment: "no-ingress",
				lagoonVersion:      "v2.7.x",
				branch:             "main2",
				projectVars:        `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:            `[]`,
				secretPrefix:       "fastly-api-",
				lagoonYAML:         "../test-resources/identify-ingress/test12/lagoon.yml",
				templatePath:       "../test-resources/output",
			},
			want: "https://node-example-project-no-ingress.example.com",
			wantRemain: []string{
				"https://node-example-project-no-ingress.example.com",
				"https://www.node-example-project-no-ingress.example.com",
				"https://en.node-example-project-no-ingress.example.com",
				"https://de.node-example-project-no-ingress.example.com",
				"https://fi.node-example-project-no-ingress.example.com",
			},
			wantautoGen: []string{
				"https://node-example-project-no-ingress.example.com",
				"https://www.node-example-project-no-ingress.example.com",
				"https://en.node-example-project-no-ingress.example.com",
				"https://de.node-example-project-no-ingress.example.com",
				"https://fi.node-example-project-no-ingress.example.com",
			},
			wantJSON: `{"primary":"https://node-example-project-no-ingress.example.com","secondary":["https://node-example-project-no-ingress.example.com","https://www.node-example-project-no-ingress.example.com","https://en.node-example-project-no-ingress.example.com","https://de.node-example-project-no-ingress.example.com","https://fi.node-example-project-no-ingress.example.com"],"autogenerated":["https://node-example-project-no-ingress.example.com","https://www.node-example-project-no-ingress.example.com","https://en.node-example-project-no-ingress.example.com","https://de.node-example-project-no-ingress.example.com","https://fi.node-example-project-no-ingress.example.com"]}`,
		},
		{
			name: "test13 no autogenerated routes",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test13/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://example.com",
			wantRemain:  []string{"https://example.com"},
			wantautoGen: []string{},
			wantJSON:    `{"primary":"https://example.com","secondary":["https://example.com"],"autogenerated":[]}`,
		},
		{
			name: "test14 only autogenerated route",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test14/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://node-example-project-main.example.com",
			wantRemain:  []string{"https://node-example-project-main.example.com"},
			wantautoGen: []string{"https://node-example-project-main.example.com"},
			wantJSON:    `{"primary":"https://node-example-project-main.example.com","secondary":["https://node-example-project-main.example.com"],"autogenerated":["https://node-example-project-main.example.com"]}`,
		},
		{
			name: "test15 only autogenerated route complex",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "sales-customer-support",
				environmentName: "develop",
				environmentType: "development",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "develop",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.ex1.example-web.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test15/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://nginx-sales-customer-support-develop.ex1.example-web.com",
			wantRemain:  []string{"https://nginx-sales-customer-support-develop.ex1.example-web.com"},
			wantautoGen: []string{"https://nginx-sales-customer-support-develop.ex1.example-web.com"},
			wantJSON:    `{"primary":"https://nginx-sales-customer-support-develop.ex1.example-web.com","secondary":["https://nginx-sales-customer-support-develop.ex1.example-web.com"],"autogenerated":["https://nginx-sales-customer-support-develop.ex1.example-web.com"]}`,
		},
		{
			name: "test16 autogenerated routes where lagoon.name of service does not match service names",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "content-example-com",
				environmentName: "feature-migration",
				environmentType: "development",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "feature/migration",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${environment}.${project}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test16/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://nginx-php.feature-migration.content-example-com.example.com",
			wantRemain:  []string{"https://nginx-php.feature-migration.content-example-com.example.com"},
			wantautoGen: []string{"https://nginx-php.feature-migration.content-example-com.example.com"},
			wantJSON:    `{"primary":"https://nginx-php.feature-migration.content-example-com.example.com","secondary":["https://nginx-php.feature-migration.content-example-com.example.com"],"autogenerated":["https://nginx-php.feature-migration.content-example-com.example.com"]}`,
		},
		{
			name: "test17 autogenerated routes with mulitple routeable services",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test17/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://nginx-example-project-main.example.com",
			wantRemain:  []string{"https://nginx-example-project-main.example.com", "https://varnish-example-project-main.example.com"},
			wantautoGen: []string{"https://nginx-example-project-main.example.com", "https://varnish-example-project-main.example.com"},
			wantJSON:    `{"primary":"https://nginx-example-project-main.example.com","secondary":["https://nginx-example-project-main.example.com","https://varnish-example-project-main.example.com"],"autogenerated":["https://nginx-example-project-main.example.com","https://varnish-example-project-main.example.com"]}`,
		},
		{
			name: "test18 autogenerated routes with wildcard and altnames",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test18/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			want:        "https://wild.example.com",
			wantRemain:  []string{"https://nginx-example-project-main.example.com", "https://wild.example.com", "https://alt.example.com", "https://www.example.com", "https://en.example.com"},
			wantautoGen: []string{"https://nginx-example-project-main.example.com"},
			wantJSON:    `{"primary":"https://wild.example.com","secondary":["https://nginx-example-project-main.example.com","https://wild.example.com","https://alt.example.com","https://www.example.com","https://en.example.com"],"autogenerated":["https://nginx-example-project-main.example.com"]}`,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// set the environment variables from args
			err := os.Setenv("MONITORING_ALERTCONTACT", tt.args.alertContact)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("MONITORING_STATUSPAGEID", tt.args.statusPageID)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("PROJECT", tt.args.projectName)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("ENVIRONMENT", tt.args.environmentName)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("BRANCH", tt.args.branch)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("LAGOON_GIT_BRANCH", tt.args.branch)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("PR_NUMBER", tt.args.prNumber)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("PR_HEAD_BRANCH", tt.args.prHeadBranch)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("PR_BASE_BRANCH", tt.args.prBaseBranch)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("ENVIRONMENT_TYPE", tt.args.environmentType)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("BUILD_TYPE", tt.args.buildType)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("ACTIVE_ENVIRONMENT", tt.args.activeEnvironment)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("STANDBY_ENVIRONMENT", tt.args.standbyEnvironment)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("LAGOON_FASTLY_NOCACHE_SERVICE_ID", tt.args.cacheNoCache)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("LAGOON_PROJECT_VARIABLES", tt.args.projectVars)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("LAGOON_ENVIRONMENT_VARIABLES", tt.args.envVars)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("LAGOON_VERSION", tt.args.lagoonVersion)
			if err != nil {
				t.Errorf("%v", err)
			}
			generator, err := generatorInput(false)
			if err != nil {
				t.Errorf("%v", err)
			}
			generator.LagoonYAML = tt.args.lagoonYAML
			// add dbaasclient overrides for tests
			generator.DBaaSClient = dbaasclient.NewClient(dbaasclient.Client{
				RetryMax:     5,
				RetryWaitMin: time.Duration(10) * time.Millisecond,
				RetryWaitMax: time.Duration(50) * time.Millisecond,
			})

			primary, remainders, autogen, err := IdentifyPrimaryIngress(generator)
			if err != nil {
				t.Errorf("%v", err)
			}

			if primary != tt.want {
				t.Errorf("returned primary %v doesn't match want %v", primary, tt.want)
			}

			if !reflect.DeepEqual(remainders, tt.wantRemain) {
				t.Errorf("returned remainders %v doesn't match want %v", remainders, tt.wantRemain)
			}

			if !reflect.DeepEqual(autogen, tt.wantautoGen) {
				t.Errorf("returned autogen %v doesn't match want %v", autogen, tt.wantautoGen)
			}

			ret := ingressIdentifyJSON{
				Primary:       primary,
				Secondary:     remainders,
				Autogenerated: autogen,
			}
			retJSON, _ := json.Marshal(ret)

			if string(retJSON) != tt.wantJSON {
				t.Errorf("returned autogen %v doesn't match want %v", string(retJSON), tt.wantJSON)
			}
		})
	}
}

func TestCreatedIngressIdentification(t *testing.T) {
	type args struct {
		alertContact       string
		statusPageID       string
		projectName        string
		environmentName    string
		branch             string
		prNumber           string
		prHeadBranch       string
		prBaseBranch       string
		environmentType    string
		buildType          string
		activeEnvironment  string
		standbyEnvironment string
		cacheNoCache       string
		serviceID          string
		secretPrefix       string
		projectVars        string
		envVars            string
		lagoonVersion      string
		lagoonYAML         string
		valuesFilePath     string
		templatePath       string
	}
	tests := []struct {
		name        string
		args        args
		want        string
		wantJSON    string
		wantRemain  []string
		wantautoGen []string
	}{
		{
			name: "test13 no autogenerated routes",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test13/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			wantRemain:  []string{"example.com"},
			wantautoGen: []string{},
			wantJSON:    `{"primary":"","secondary":["example.com"],"autogenerated":[]}`,
		},
		{
			name: "test14 only autogenerated route",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test14/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			wantRemain:  []string{},
			wantautoGen: []string{"node"},
			wantJSON:    `{"primary":"","secondary":[],"autogenerated":["node"]}`,
		},
		{
			name: "test15 only autogenerated route complex",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "sales-customer-support",
				environmentName: "develop",
				environmentType: "development",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "develop",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.ex1.example-web.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test15/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			wantRemain:  []string{},
			wantautoGen: []string{"nginx"},
			wantJSON:    `{"primary":"","secondary":[],"autogenerated":["nginx"]}`,
		},
		{
			name: "test16 autogenerated routes where lagoon.name of service does not match service names",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "content-example-com",
				environmentName: "feature-migration",
				environmentType: "development",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "feature/migration",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${environment}.${project}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test16/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			wantRemain:  []string{},
			wantautoGen: []string{"nginx-php"},
			wantJSON:    `{"primary":"","secondary":[],"autogenerated":["nginx-php"]}`,
		},
		{
			name: "test17 autogenerated routes with mulitple routeable services",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test17/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			wantRemain:  []string{},
			wantautoGen: []string{"nginx", "varnish"},
			wantJSON:    `{"primary":"","secondary":[],"autogenerated":["nginx","varnish"]}`,
		},
		{
			name: "test18 autogenerated routes with wildcard and altnames",
			args: args{
				alertContact:    "alertcontact",
				statusPageID:    "statuspageid",
				projectName:     "example-project",
				environmentName: "main",
				environmentType: "production",
				buildType:       "branch",
				lagoonVersion:   "v2.7.x",
				branch:          "main",
				projectVars:     `[{"name":"LAGOON_SYSTEM_ROUTER_PATTERN","value":"${service}-${project}-${environment}.example.com","scope":"internal_system"}]`,
				envVars:         `[]`,
				lagoonYAML:      "../test-resources/identify-ingress/test18/lagoon.yml",
				templatePath:    "../test-resources/output",
			},
			wantRemain:  []string{"wildcard-wild.example.com", "alt.example.com"},
			wantautoGen: []string{"nginx"},
			wantJSON:    `{"primary":"","secondary":["wildcard-wild.example.com","alt.example.com"],"autogenerated":["nginx"]}`,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// set the environment variables from args
			err := os.Setenv("MONITORING_ALERTCONTACT", tt.args.alertContact)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("MONITORING_STATUSPAGEID", tt.args.statusPageID)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("PROJECT", tt.args.projectName)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("ENVIRONMENT", tt.args.environmentName)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("BRANCH", tt.args.branch)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("LAGOON_GIT_BRANCH", tt.args.branch)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("PR_NUMBER", tt.args.prNumber)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("PR_HEAD_BRANCH", tt.args.prHeadBranch)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("PR_BASE_BRANCH", tt.args.prBaseBranch)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("ENVIRONMENT_TYPE", tt.args.environmentType)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("BUILD_TYPE", tt.args.buildType)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("ACTIVE_ENVIRONMENT", tt.args.activeEnvironment)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("STANDBY_ENVIRONMENT", tt.args.standbyEnvironment)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("LAGOON_FASTLY_NOCACHE_SERVICE_ID", tt.args.cacheNoCache)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("LAGOON_PROJECT_VARIABLES", tt.args.projectVars)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("LAGOON_ENVIRONMENT_VARIABLES", tt.args.envVars)
			if err != nil {
				t.Errorf("%v", err)
			}
			err = os.Setenv("LAGOON_VERSION", tt.args.lagoonVersion)
			if err != nil {
				t.Errorf("%v", err)
			}
			generator, err := generatorInput(false)
			if err != nil {
				t.Errorf("%v", err)
			}
			generator.LagoonYAML = tt.args.lagoonYAML
			// add dbaasclient overrides for tests
			generator.DBaaSClient = dbaasclient.NewClient(dbaasclient.Client{
				RetryMax:     5,
				RetryWaitMin: time.Duration(10) * time.Millisecond,
				RetryWaitMax: time.Duration(50) * time.Millisecond,
			})

			autogen, remainders, err := CreatedIngressIdentification(generator)
			if err != nil {
				t.Errorf("%v", err)
			}

			if !reflect.DeepEqual(autogen, tt.wantautoGen) {
				t.Errorf("returned autogen %v doesn't match want %v", autogen, tt.wantautoGen)
			}

			if !reflect.DeepEqual(remainders, tt.wantRemain) {
				t.Errorf("returned remainders %v doesn't match want %v", remainders, tt.wantRemain)
			}

			ret := ingressIdentifyJSON{
				Autogenerated: autogen,
				Secondary:     remainders,
			}
			retJSON, _ := json.Marshal(ret)

			if string(retJSON) != tt.wantJSON {
				t.Errorf("returned autogen %v doesn't match want %v", string(retJSON), tt.wantJSON)
			}
		})
	}
}
