---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    lagoon.sh/branch: brancha
    lagoon.sh/version: v2.x.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: nginx-php-persistent
    lagoon.sh/buildType: branch
    lagoon.sh/environment: brancha
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: nginx
    lagoon.sh/service-type: nginx-php-persistent
  name: nginx-hpa
spec:
  maxReplicas: 16
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 1500
        type: Utilization
    type: Resource
  minReplicas: 8
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
status:
  currentMetrics: null
  desiredReplicas: 0
