apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash.fullname" . }}
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
  annotations:
    {{- include "mariadb-shared.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9600
      protocol: TCP
      name: 9600-tcp
  selector:
    {{- include "logstash.selectorLabels" . | nindent 4 }}
