apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastly-api-secret.fullname" . }}
  labels:
    {{- include "fastly-api-secret.labels" . | nindent 4 }}
  annotations:
    {{- include "fastly-api-secret.annotations" . | nindent 4 }}
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4  }}
    {{- end }}
stringData:
  api-token: {{ .Values.fastly.apiToken }}
  platform-tls-configuration: {{ .Values.fastly.platformTLSConfiguration }}
