apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "python-persistent.persistentStorageName" . }}
  labels:
    {{- include "python-persistent.labels" . | nindent 4 }}
  annotations:
    k8up.syn.tools/backup: "true"
    {{- include "python-persistent.annotations" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: bulk
  resources:
    requests:
      storage: {{ .Values.persistentStorage.size | quote }}
