package generator

import (
	"github.com/uselagoon/build-deploy-tool/internal/dbaasclient"
	"github.com/uselagoon/build-deploy-tool/internal/lagoon"
	autoscalingv2 "k8s.io/api/autoscaling/v2"
	corev1 "k8s.io/api/core/v1"
	policyv1 "k8s.io/api/policy/v1"
)

// BuildValues is the values file data generated by the lagoon build
type BuildValues struct {
	Project                       string                       `json:"project"`
	Environment                   string                       `json:"environment"`
	EnvironmentType               string                       `json:"environmentType"`
	Namespace                     string                       `json:"namespace"`
	GitSha                        string                       `json:"gitSha"`
	BuildType                     string                       `json:"buildType"`
	Kubernetes                    string                       `json:"kubernetes"`
	LagoonVersion                 string                       `json:"lagoonVersion"`
	ActiveEnvironment             string                       `json:"activeEnvironment"`
	StandbyEnvironment            string                       `json:"standbyEnvironment"`
	IsActiveEnvironment           bool                         `json:"isActiveEnvironment"`
	IsStandbyEnvironment          bool                         `json:"isStandbyEnvironment"`
	PodSecurityContext            *corev1.PodSecurityContext   `json:"podSecurityContext"`
	ImagePullSecrets              []string                     `json:"imagePullSecrets"`
	PrivateRegistryURLS           []string                     `json:"privateRegistryURLS"`
	Branch                        string                       `json:"branch"`
	PRNumber                      string                       `json:"prNumber"`
	PRTitle                       string                       `json:"prTitle"`
	PRHeadBranch                  string                       `json:"prHeadBranch"`
	PRBaseBranch                  string                       `json:"prBaseBranch"`
	Fastly                        Fastly                       `json:"fastly"`
	FastlyCacheNoCache            string                       `json:"fastlyCacheNoCahce"`
	FastlyAPISecretPrefix         string                       `json:"fastlyAPISecretPrefix"`
	ConfigMapSha                  string                       `json:"configMapSha"`
	Route                         string                       `json:"route"`
	Routes                        []string                     `json:"routes"`
	AutogeneratedRoutes           []string                     `json:"autogeneratedRoutes"`
	RoutesAutogeneratePrefixes    []string                     `json:"routesAutogeneratePrefixes"`
	AutogeneratedRoutesFastly     bool                         `json:"autogeneratedRoutesFastly"`
	Services                      []ServiceValues              `json:"services"`
	Backup                        BackupConfiguration          `json:"backup"`
	Monitoring                    MonitoringConfig             `json:"monitoring"`
	DBaaSOperatorEndpoint         string                       `json:"dbaasOperatorEndpoint"`
	ServiceTypeOverrides          *lagoon.EnvironmentVariable  `json:"serviceTypeOverrides"`
	DBaaSEnvironmentTypeOverrides *lagoon.EnvironmentVariable  `json:"dbaasEnvironmentTypeOverrides"`
	DBaaSFallbackSingle           bool                         `json:"dbaasFallbackSingle"`
	IngressClass                  string                       `json:"ingressClass"`
	TaskScaleMaxIterations        int                          `json:"taskScaleMaxIterations"`
	TaskScaleWaitTime             int                          `json:"taskScaleWaitTime"`
	ImageCache                    string                       `json:"imageCache"`
	DefaultBackupSchedule         string                       `json:"defaultBackupSchedule"`
	DBaaSClient                   *dbaasclient.Client          `json:"-"`
	ResourceWorkloads             map[string]ResourceWorkloads `json:"resourceWorkloads"`
	ResourceWorkloadOverrides     string                       `json:"resourceWorkloadOverrides"`
}

type ResourceWorkloads struct {
	ServiceType string     `json:"serviceType"`
	HPA         *HPASpec   `json:"hpa,omitempty"`
	PDB         *PDBSpec   `json:"pdb,omitempty"`
	Resources   []Resource `json:"resources"`
}

type Resource struct {
	Name      string                      `json:"name"`
	Resources corev1.ResourceRequirements `json:"resources"`
}

type HPASpec struct {
	Spec autoscalingv2.HorizontalPodAutoscalerSpec `json:"spec"`
}

type PDBSpec struct {
	Spec policyv1.PodDisruptionBudgetSpec `json:"spec"`
}

type Resources map[string]corev1.ResourceRequirements

type Fastly struct {
	ServiceID     string `json:"serviceId"`
	APISecretName string `json:"apiSecretName"`
	Watch         bool   `json:"watch"`
}

type MonitoringConfig struct {
	Enabled      bool   `json:"enabled"`
	AlertContact string `json:"alertContact"`
	StatusPageID string `json:"statusPageID"`
}

// ServiceValues is the values for a specific service used by a lagoon build
type ServiceValues struct {
	Name                          string                   `json:"name"`         // this is the actual compose service name
	OverrideName                  string                   `json:"overrideName"` // if an override name is provided, use it
	Type                          string                   `json:"type"`
	AutogeneratedRoutesEnabled    bool                     `json:"autogeneratedRoutesEnabled"`
	AutogeneratedRoutesTLSAcme    bool                     `json:"autogeneratedRoutesTLSAcme"`
	AutogeneratedRouteDomain      string                   `json:"autogeneratedRouteDomain"`
	ShortAutogeneratedRouteDomain string                   `json:"shortAutogeneratedRouteDomain"`
	DBaaSEnvironment              string                   `json:"dbaasEnvironment"`
	NativeCronjobs                map[string]CronjobValues `json:"nativeCronjobs"`
	InPodCronjobs                 string                   `json:"inPodCronjobs"`
	ImageName                     string                   `json:"imageName"`
	DeploymentServiceType         string                   `json:"deploymentServiecType"`
	ServicePort                   int32                    `json:"servicePort,omitempty"`
	PersistentVolumePath          string                   `json:"persistentVolumePath,omitempty"`
	PersistentVolumeName          string                   `json:"persistentVolumeName,omitempty"`
	PersistentVolumeSize          string                   `json:"persistentVolumeSize,omitempty"`
	UseSpotInstances              bool                     `json:"useSpot"`
	NodeSelectors                 *map[string]string       `json:"nodeSelectors"`
	Tolerations                   *[]corev1.Toleration     `json:"tolerations"`
	Affinity                      *corev1.Affinity         `json:"affinity"`
	CronjobUseSpotInstances       bool                     `json:"cronjobUseSpot"`
	CronjobNodeSelectors          *map[string]string       `json:"cronjobNodeSelectors"`
	CronjobTolerations            *[]corev1.Toleration     `json:"cronjobTolerations"`
	CronjobAffinity               *corev1.Affinity         `json:"cronjobAffinity"`
	DBaasReadReplica              bool                     `json:"dBaasReadReplica"`
	ResourceWorkload              string                   `json:"resourceWorkload,omitempty"`
}

// CronjobValues is the values for cronjobs
type CronjobValues struct {
	Schedule string `json:"schedule"`
	Command  string `json:"command"`
}

type BackupConfiguration struct {
	K8upVersion    string                      `json:"k8upVersion"`
	PruneRetention PruneRetention              `json:"pruneRetention"`
	PruneSchedule  string                      `json:"pruneSchedule"`
	CheckSchedule  string                      `json:"checkSchedule"`
	BackupSchedule string                      `json:"backupSchedule"`
	S3Endpoint     string                      `json:"s3Endpoint"`
	S3BucketName   string                      `json:"s3BucketName"`
	S3SecretName   string                      `json:"s3SecretName"`
	CustomLocation CustomBackupRestoreLocation `json:"customLocation"`
}

type CustomBackupRestoreLocation struct {
	BackupLocationAccessKey  string `json:"backupLocationAccessKey"`
	BackupLocationSecretKey  string `json:"backupLocationSecretKey"`
	RestoreLocationAccessKey string `json:"restoreLocationAccessKey"`
	RestoreLocationSecretKey string `json:"restoreLocationSecretKey"`
}

type PruneRetention struct {
	Hourly  int `json:"hourly"`
	Daily   int `json:"daily"`
	Weekly  int `json:"weekly"`
	Monthly int `json:"monthly"`
}
