apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-single.fullname" . }}
  labels:
    {{- include "mongodb-single.labels" . | nindent 4 }}
  annotations:
    {{- include "mongodb-single.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 27017
      protocol: TCP
      name: 27017-tcp
  selector:
    {{- include "mongodb-single.selectorLabels" . | nindent 4 }}
