version: '2.3'

x-project:
  &project ${PROJECT:-example-project}

x-volumes:
  &default-volumes
  volumes:

    - .:/app:${VOLUME_FLAGS:-delegated} ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
x-user:
  &default-user
  user: '1000'

x-environment:
  &default-environment
  LAGOON_LOCALDEV_URL: &default-url ${LOCALDEV_URL:-example-project.docker.amazee.io}
  LAGOON_ROUTE: *default-url
  XDEBUG_ENABLE: ${XDEBUG_ENABLE:-}
  CI: ${CI:-}
  DOCKERHOST: ${DOCKERHOST:-host.docker.internal}
  PHP_MEMORY_LIMIT: "2G"
  PHP_APC_SHM_SIZE: "256M"
  PHP_MAX_EXECUTION_TIME: -1
  PHP_MAX_INPUT_VARS: 4000

  LAGOON_PROJECT: *project

  LAGOON_ENVIRONMENT_TYPE: ${LAGOON_ENVIRONMENT_TYPE:-local}

services:

  cli:
    build:
      context: .
      dockerfile: .docker/Dockerfile.cli
    image: *project
    <<: *default-volumes
    user: root
    environment:
      <<: *default-environment
    volumes_from: ### Local overrides to mount host SSH keys. Automatically removed in CI.
      - container:amazeeio-ssh-agent ### Local overrides to mount host SSH keys. Automatically removed in CI.
    ports:
      - "35729"
    labels:
      lagoon.type: cli-persistent
      lagoon.persistent.name: nginx-php
      lagoon.persistent: /app/docroot/sites/default/files/
  nginx:
    build:
      context: .
      dockerfile: .docker/Dockerfile.nginx-drupal
      args:
        CLI_IMAGE: *project
    <<: *default-volumes
    <<: *default-user
    environment:
      <<: *default-environment
    depends_on:
      - cli
    networks:
      - amazeeio-network
      - default
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.name: nginx-php
      lagoon.persistent: /app/docroot/sites/default/files/
      lagoon.persistent.class: slow

  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile.php
      args:
        CLI_IMAGE: *project
    <<: *default-volumes
    <<: *default-user
    environment:
      <<: *default-environment
    depends_on:
      - cli
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.name: nginx-php
      lagoon.persistent: /app/docroot/sites/default/files/
      lagoon.persistent.class: slow

  mariadb:
    build:
      context: .
      dockerfile: .docker/Dockerfile.mariadb
      args:
        IMAGE: "${DATABASE_IMAGE:-amazeeio/mariadb-drupal:21.7.0}"
    environment:
      <<: *default-environment
    ports:
      - "3306"
    labels:
      lagoon.type: mariadb
  redis:
    image: amazeeio/redis:6-21.11.0
    labels:
      lagoon.type: redis
    environment:
      << : *default-environment

  chrome:
    image: selenium/standalone-chrome:3.141.59-oxygen
    shm_size: '1gb'
    <<: *default-volumes
    environment:
      <<: *default-environment
    depends_on:
      - cli
    labels:
      lagoon.type: none

  wait_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - cli
      - mariadb
    command: mariadb:3306
    labels:
      lagoon.type: none
networks:
  amazeeio-network:
    external: true
volumes:
  app: {}