---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    lagoon.sh/branch: environment-name
    lagoon.sh/version: v2.x.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: solr
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: solr-php-persistent
    lagoon.sh/buildType: branch
    lagoon.sh/environment: environment-name
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: solr
    lagoon.sh/service-type: solr-php-persistent
    lagoon.sh/template: solr-php-persistent-0.1.0
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: solr
      app.kubernetes.io/name: solr-php-persistent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8up.syn.tools/backupcommand: /bin/sh -c 'tar -cf - -C "/var/solr" --exclude="lost\+found"
          . || [ $? -eq 1 ]'
        k8up.syn.tools/file-extension: .solr.tar
        lagoon.sh/branch: environment-name
        lagoon.sh/configMapSha: 32bf1359ac92178c8909f0ef938257b477708aa0d78a5a15ad7c2d7919adf273
        lagoon.sh/version: v2.x.x
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: solr
        app.kubernetes.io/managed-by: build-deploy-tool
        app.kubernetes.io/name: solr-php-persistent
        lagoon.sh/buildType: branch
        lagoon.sh/environment: environment-name
        lagoon.sh/environmentType: production
        lagoon.sh/project: example-project
        lagoon.sh/service: solr
        lagoon.sh/service-type: solr-php-persistent
        lagoon.sh/template: solr-php-persistent-0.1.0
    spec:
      containers:
      - env:
        - name: LAGOON_GIT_SHA
          value: "0"
        - name: CRONJOBS
        - name: SERVICE_NAME
          value: solr
        envFrom:
        - configMapRef:
            name: lagoon-env
        image: harbor.example.com/example-project/environment-name/solr@latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 90
          tcpSocket:
            port: 8983
          timeoutSeconds: 3
        name: solr
        ports:
        - containerPort: 8983
          name: 8983-tcp
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 3
          tcpSocket:
            port: 8983
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext: {}
        volumeMounts:
        - mountPath: /var/solr
          name: solr
      enableServiceLinks: false
      imagePullSecrets:
      - name: lagoon-internal-registry-secret
      priorityClassName: lagoon-priority-production
      securityContext:
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
      volumes:
      - name: solr
        persistentVolumeClaim:
          claimName: solr
status: {}
