---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    lagoon.sh/branch: environment-name
    lagoon.sh/version: v2.x.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: varnish
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: varnish
    lagoon.sh/buildType: branch
    lagoon.sh/environment: environment-name
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: varnish
    lagoon.sh/service-type: varnish
    lagoon.sh/template: varnish-0.1.0
  name: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: varnish
      app.kubernetes.io/name: varnish
  strategy: {}
  template:
    metadata:
      annotations:
        lagoon.sh/branch: environment-name
        lagoon.sh/configMapSha: 32bf1359ac92178c8909f0ef938257b477708aa0d78a5a15ad7c2d7919adf273
        lagoon.sh/version: v2.x.x
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: varnish
        app.kubernetes.io/managed-by: build-deploy-tool
        app.kubernetes.io/name: varnish
        lagoon.sh/buildType: branch
        lagoon.sh/environment: environment-name
        lagoon.sh/environmentType: production
        lagoon.sh/project: example-project
        lagoon.sh/service: varnish
        lagoon.sh/service-type: varnish
        lagoon.sh/template: varnish-0.1.0
    spec:
      containers:
      - env:
        - name: LAGOON_GIT_SHA
          value: "0"
        - name: CRONJOBS
        - name: SERVICE_NAME
          value: varnish
        envFrom:
        - configMapRef:
            name: lagoon-env
        image: harbor.example.com/example-project/environment-name/varnish@latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 60
          tcpSocket:
            port: 8080
          timeoutSeconds: 10
        name: varnish
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 6082
          name: controlport
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext: {}
      enableServiceLinks: false
      imagePullSecrets:
      - name: lagoon-internal-registry-secret
      priorityClassName: lagoon-priority-production
      securityContext:
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 0
        runAsUser: 10000
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    lagoon.sh/branch: environment-name
    lagoon.sh/version: v2.x.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: varnish-persist
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: varnish-persistent
    lagoon.sh/buildType: branch
    lagoon.sh/environment: environment-name
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: varnish-persist
    lagoon.sh/service-type: varnish-persistent
    lagoon.sh/template: varnish-persistent-0.1.0
  name: varnish-persist
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: varnish-persist
      app.kubernetes.io/name: varnish-persistent
  strategy: {}
  template:
    metadata:
      annotations:
        k8up.syn.tools/backupcommand: /bin/sh -c "/bin/busybox tar -cf - -C /var/cache/varnish
          ."
        k8up.syn.tools/file-extension: .varnish-persist.tar
        lagoon.sh/branch: environment-name
        lagoon.sh/configMapSha: 32bf1359ac92178c8909f0ef938257b477708aa0d78a5a15ad7c2d7919adf273
        lagoon.sh/version: v2.x.x
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: varnish-persist
        app.kubernetes.io/managed-by: build-deploy-tool
        app.kubernetes.io/name: varnish-persistent
        lagoon.sh/buildType: branch
        lagoon.sh/environment: environment-name
        lagoon.sh/environmentType: production
        lagoon.sh/project: example-project
        lagoon.sh/service: varnish-persist
        lagoon.sh/service-type: varnish-persistent
        lagoon.sh/template: varnish-persistent-0.1.0
    spec:
      containers:
      - env:
        - name: LAGOON_GIT_SHA
          value: "0"
        - name: CRONJOBS
        - name: SERVICE_NAME
          value: varnish-persist
        envFrom:
        - configMapRef:
            name: lagoon-env
        image: harbor.example.com/example-project/environment-name/varnish-persist@latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 60
          tcpSocket:
            port: 8080
          timeoutSeconds: 10
        name: varnish
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 6082
          name: controlport
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext: {}
        volumeMounts:
        - mountPath: /var/cache/varnish
          name: varnish-persist
      enableServiceLinks: false
      imagePullSecrets:
      - name: lagoon-internal-registry-secret
      priorityClassName: lagoon-priority-production
      securityContext:
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 0
        runAsUser: 10000
      volumes:
      - name: varnish-persist
        persistentVolumeClaim:
          claimName: varnish-persist
status: {}
