apiVersion: postgres.amazee.io/v1
kind: PostgreSQLConsumer
metadata:
  name: {{ include "postgres-dbaas.fullname" . }}
  labels:
    {{- include "postgres-dbaas.labels" . | nindent 4 }}
  annotations:
    {{- include "postgres-dbaas.annotations" . | nindent 4 }}

spec:
  environment: {{ .Values.environment}}