---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    lagoon.sh/branch: environment-name
    lagoon.sh/version: v2.x.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: mongodb-single
    lagoon.sh/buildType: branch
    lagoon.sh/environment: environment-name
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: mongodb
    lagoon.sh/service-type: mongodb-single
    lagoon.sh/template: mongodb-single-0.1.0
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/name: mongodb-single
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8up.syn.tools/backupcommand: /bin/sh -c 'tar -cf - -C "/data/db" --exclude="lost\+found"
          . || [ $? -eq 1 ]'
        k8up.syn.tools/file-extension: .mongodb.tar
        lagoon.sh/branch: environment-name
        lagoon.sh/configMapSha: 32bf1359ac92178c8909f0ef938257b477708aa0d78a5a15ad7c2d7919adf273
        lagoon.sh/version: v2.x.x
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/managed-by: build-deploy-tool
        app.kubernetes.io/name: mongodb-single
        lagoon.sh/buildType: branch
        lagoon.sh/environment: environment-name
        lagoon.sh/environmentType: production
        lagoon.sh/project: example-project
        lagoon.sh/service: mongodb
        lagoon.sh/service-type: mongodb-single
        lagoon.sh/template: mongodb-single-0.1.0
    spec:
      containers:
      - env:
        - name: LAGOON_GIT_SHA
          value: "0"
        - name: CRONJOBS
        - name: SERVICE_NAME
          value: mongodb
        envFrom:
        - configMapRef:
            name: lagoon-env
        image: harbor.example.com/example-project/environment-name/mongodb@latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 120
          periodSeconds: 5
          tcpSocket:
            port: 27017
        name: mongodb-single
        ports:
        - containerPort: 27017
          name: 27017-tcp
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 1
          tcpSocket:
            port: 27017
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb
      enableServiceLinks: true
      imagePullSecrets:
      - name: lagoon-internal-registry-secret
      priorityClassName: lagoon-priority-production
      securityContext:
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
      volumes:
      - name: mongodb
        persistentVolumeClaim:
          claimName: mongodb
status: {}
