version: '3.2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: node
  nginx:
    build:
      context: .
      dockerfile: .nginx/Dockerfile
    labels:
      lagoon.type: nginx