name: Publish build-deploy-image

on:
  push:
    branches:
      - 'main'
      - 'build-image'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'
      - 'release/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion:
        - 1.25
    steps:
      -
        name: Checkout PR
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: "0"
          ref: ${{ github.event.pull_request.head.sha }}
      -
        name: Checkout Branch or Tag
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: "0"
      -
        name: Set version for non-tag build
        if: "!startsWith(github.ref, 'refs/tags/')"
        id: version_non-tag_build
        run: |
          VERSION=$(echo $(git describe --abbrev=0 --tags)+$(git rev-parse --short=8 HEAD))
          DOCKER_TAG=$(echo $(git describe --abbrev=0 --tags)-$(git rev-parse --short=8 HEAD))
          BUILD=$(date +%FT%T%z)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV
          echo "build-deploy-tool $VERSION (built: $BUILD / go ${{ matrix.goversion }})"
      -
        name: Set version for tag build
        if: "startsWith(github.ref, 'refs/tags/')"
        id: version_tag_build
        run: |
          VERSION=$(echo $(git describe --abbrev=0 --tags))
          BUILD=$(date +%FT%T%z)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DOCKER_TAG=$VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV
          echo "build-deploy-tool $VERSION (built: $BUILD / go ${{ matrix.goversion }})"
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ github.repository_owner }}/build-deploy-image
            ghcr.io/${{ github.repository_owner }}/build-deploy-image
          tags: |
            # set edge tag for default branch
            type=edge,enable={{is_default_branch}}
            # set tag+build for default branch
            type=raw,value=${{ env.DOCKER_TAG}},enable={{is_default_branch}}
            # tag event
            type=ref,event=tag
            # pull request event
            type=ref,event=pr
            # pull request event
            type=ref,event=branch
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
        with:
          buildkitd-flags: --debug
      -
        name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        id: cache
        with:
          path: |
            go-mod
            go-build
          key: cache-${{ hashFiles('**/go.mod') }}
      - 
        name: inject cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "go-mod": "/go/pkg/mod",
              "go-build": "/root/.cache/go-build"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            "VERSION=${{ env.VERSION }}"
            "BUILD=${{ env.BUILD }}"
            "GO_VER=${{ matrix.goversion }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@bacf462e8d090c09660de30a6ccc718035f961e3 # v1.20.4
        with:
          command: compare
          image: docker.io/${{ github.repository_owner }}/build-deploy-image@${{ steps.build.outputs.digest }}
          to: docker.io/${{ github.repository_owner }}/build-deploy-image:main
          ignore-unchanged: true
          only-severities: critical,high
          sarif-file: scout-report.sarif
          github-token: ${{ secrets.GITHUB_TOKEN }}
