name: Publish lagoon-core build-deploy image

on:
  push:
    tags:
      - 'core-v*.*.*'

permissions: {}

jobs:
  docker:
    permissions:
      # checkout
      contents: read
      # push image to ghcr
      packages: write
      # attest-build-provenance
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion:
        - 1.23
    steps:
      -
        name: Checkout Branch or Tag
        uses: actions/checkout@v4
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: "0"
      -
        name: Set version for tag build
        if: "startsWith(github.ref, 'refs/tags/')"
        id: version_tag_build
        run: |
          LAGOON_VERSION=$(echo $(git describe --abbrev=0 --tags --match 'core-v*'))
          BUILD_VERSION=$(echo $(git describe --abbrev=0 --tags --match 'v*'))
          BUILD=$(date +%FT%T%z)
          echo "LAGOON_VERSION=$LAGOON_VERSION" >> $GITHUB_ENV
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV
          echo "build-deploy $BUILD_VERSION (built: $BUILD) tagged as $LAGOON_VERSION"
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ github.repository_owner }}/build-deploy-image
            ghcr.io/${{ github.repository_owner }}/build-deploy-image
          tags: |
            # tag event
            type=ref,event=tag
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            "VERSION=${{ env.LAGOON_VERSION }}"
            "BUILD=${{ env.BUILD }}"
            "GO_VER=${{ matrix.goversion }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Attest dockerhub image
        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
        with:
          subject-digest: ${{steps.build-and-push.outputs.digest}}
          subject-name: index.docker.io/${{ github.repository_owner }}/build-deploy-image
          push-to-registry: true

      - name: Attest ghcr image
        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
        with:
          subject-digest: ${{steps.build-and-push.outputs.digest}}
          subject-name: ghcr.io/${{ github.repository_owner }}/build-deploy-image
          push-to-registry: true
